name: Run API Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        env:
          AUTH_TOKEN: ${{ secrets.AuthToken }}
        run: npm test

      - name: Collect test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/
